image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

deploy:
  stage: deploy
  script:
    - yarn global add firebase-tools # Firebase CLIをYarnを使ってインストール
    - firebase deploy --token $FIREBASE_TOKEN # Firebaseプロジェクトにデプロイ